### ISSUE TITLE
切换Buffer的时候最好重新update一下Lines

### ISSUE THREAD

**Issue by Xx1gS** [noearc/jieba-lua#1]
重新进入nvim恢复之前的session会没有办法使用分词；
编辑完一个文件切换另一个Buffer的时候也会没有办法立即适应当前环境中的Lines。

最好在触发事件里加入BufEnter。
```lua
vim.api.nvim_create_autocmd({ "InsertLeave", "TextChanged", "TextChangedI", "BufEnter" }, { callback = update_lines })
``` 

不过我感觉是不是频繁切换重新调用计算开销会很大，能不能把计算范围缩小到当前可视页面，或者每次只计算上一个或下一个分词的位置。

**Comment by Xx1gS** [comment]
啊，我发错仓库了，抱歉。 [jieba.nvim](https://github.com/noearc/jieba.nvim)这里才对

**Comment by noearc** [comment]
收到，确实是这样，没想到已经有人开始用了啊hh，bufenter加了，只计算可视界面应该不是很必要，因为本来就是按行行分词的，性能影响不大，lines只是存一个整个文件待读取
当然改一次就从头更新这个表也有些浪费是确实，后续测试大文件不行的话可能会优化一下
